# nych_codec.py — NYCH 2.0 Invariant Glyph Set (Direct, Lossless)

GEOMETRY = {
    'X': '🔴',  # X-axis
    'Y': '⚪',  # Y-axis
    'Z': '🟡',  # Z-axis
    'STEP': '▶️',
    'DOUBLE_STEP': '⏩',
    'END': '⏭️',
    'POS_TWIST': '🔺',
    'NEG_TWIST': '🔻',
    'HALF_TWIST': 'YXZ',  # explicit sequence for inversion
    'CLOSURE': '♾️'
}

SWITCH = {
    'VOLTAGE': '♈',
    'RESISTANCE': '♎',
    'CAPACITANCE': '⛎',
    'CURRENT': '♓',
    'FREQUENCY': '♒',
    'PHASE_ANGLE': '♐',
    'INDUCTANCE': '♉',
    'OPEN': '🟥',
    'CLOSED': '🟩',
    'MOMENTARY': '🔰',
    'POWER_ON': '🔆',
    'LAMP_ON': '💡',
    'LAMP_OFF': '🔲💡',
    'LAMP_FAILED': '❌💡',
    'HEATER': '🔥',
    'MOTOR': '🎡',
    'WIRE': '🔌',
    'JUNCTION': '❇️',
    'SPLIT': '✴️',
    'MERGE': '👫',
    'FORWARD_DIODE': '👉',
    'REVERSE_DIODE': '👈',
    'LED': '🔸',
    'ZENER': '🔶',
    'DC_SOURCE': '🔋',
    'AC_SOURCE': '🔌',
    'CURRENT_SOURCE': '⚛️',
    'PULSED_SOURCE': '☎️',
    'TEMP_SENSOR': '🌡️',
    'AUDIO_SENSOR': '🎙️',
    'RF_SENSOR': '📡',
    'OPTICAL_SENSOR': '📷',
    'HALL_SENSOR': '⛲',
    'SHORT': '💥',
    'BLOWN_FUSE': '🍢',
    'SLEEP': '💤',
    'RAMP_UP': '🛫',
    'DECAY': '🛬',
    'NOISE': '🏟️',
    'RINGING': '🎵',
    'CLIPPING': '🥢',
    'OVERLOAD': '🚨',
    'LEAKAGE': '💦',
    'SLOW_TRANSIENT': '🐢',
    'PROBE': '🖖',
    'REF_NODE': '🎯',
    'DIGITS': ['0️⃣','1️⃣','2️⃣','3️⃣','4️⃣','5️⃣','6️⃣','7️⃣','8️⃣','9️⃣'],
    'EXPONENTS': ['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹'],
    'FRACTIONS': ['½','¼','¾'],
}

BOOLEAN = {
    'FALSE': '🛑',
    'TRUE': '✔️',
    'STRONG_TRUE': '💯',
    'NOT': '🚫',
    'NOR': '⛔',
    'AND': '🔗',
    'OR': '📎',
    'XOR': '🖇️',
    'NAND': '⛓️‍💥',
    'HIGH': '🔺',
    'LOW': '🔻',
    'FORWARD': '👉',
    'BACKWARD': '👈'
}

BINARY = {
    'BIT_1': '1️⃣',
    'BIT_0': '0️⃣',
    'BYTE': '8️⃣⏹️',
    'WORD16': '1️⃣6️⃣⏹️',
    'WORD32': '3️⃣2️⃣⏹️',
    'WORD64': '6️⃣4️⃣⏹️'
}

GATE = {
    'GENERIC': '🔲',
    'AND': '🔗',
    'OR': '📎',
    'XOR': '🖇️',
    'NAND': '⛓️‍💥',
    'NOT': '🚫',
    'NOR': '⛔'
}

MATH = {
    'ADD': '➕',
    'SUB': '➖',
    'MUL': '✖️',
    'DIV': '➗',
    'EQUAL': '🟰',
    'NOT_EQUAL': '❌',
    'EXP': 'ⁿ',
    'SQRT': '√',
    'CBRT': '∛',
    'NTHRT': '∜',
    'POSITIVE': '➕️⃣',
    'NEGATIVE': '➖️⃣',
    'ABS': '📏',
    'GAIN': '🎚️',
    'GT': '🔼',
    'LT': '🔽',
    'GEQ': '🔼🟰',
    'LEQ': '🔽🟰',
    'INCR_FN': '👌',
    'DECR_FN': '🤏',
    'PERIODIC': '📰',
    'SIN': '✒️',
    'COS': '🖋️🖊️',
    'TAN': '🏹',
    'EXP_FUNC': '🍶',
    'LOG10': '📓',
    'LN': '📚',
    'SUM': '🗃️',
    'INT': '🏮',
    'DERIV': '💷',
    'MEAN': '💶',
    'DISCRETE_SUM': '💴',
    'SCALAR': '🔦',
    'VECTOR': '📟',
    'MATRIX': '⌨️',
    'TENSOR': '🌂',
    'RAND': '🎲',
    'DISTRIBUTION': '🪣',
    'EXPECTED': '👓',
    'VARIANCE': '🗳️',
    'STD_DEV': '📮'
}

FRACTAL = {
    'FRACTAL': '🌟',
    'ITER_MAP': '🗺️',
    'JULIA': '🎉',
    'MANDELBROT': '🎊',
    'SIERPINSKI': '🪅',
    'L_SYSTEM': '🗾',
    'INFINITE': '🪡',
    'LIMIT_CYCLE': '🚳',
    'CHAOTIC': '💣',
    'LORENZ': '🥨',
    'FIXED_POINT': '🍡',
    'STRANGE_ATTRACTOR': '💅',
    'DIVERGENCE': '✨',
    'BASIN_CAPTURE': '🪝',
    'DRIFT': '🫗',
    'HIGH_DIM_ATTRACTOR': '🍩',
    'LOGISTIC_MAP': '🛣️',
    'CURRENT_MAP': '🗞️',
    'SENSITIVITY': '🔇',
    'BIFURCATION': '🚼'
}

HEDRON = {
    'AMPLITUDE': '🎚️',
    'MAGNITUDE': '🧮',
    'AMP_UP': '🔉⬆️',
    'AMP_DOWN': '🔉⬇️',
    'AMP_LOW': '🔈',
    'AMP_HIGH': '🔊',
    'HARMONIC_AMP': '🎶',
    'COHERENCE': '🚻',
    'STABLE': '🧑‍🧑‍🧒‍🧒',
    'SEMI_STABLE': '🧑‍🧑‍🧒',
    'DECOHERING': '🧑‍🧒',
    'FROZEN': '🧊',
    'RESONANCE_SPIKE': '〽️',
    'PROBABILITY': '🎲',
    'DISTRIBUTION': '🧱',
    'MEAN': '💱',
    'UNKNOWN': '🦹‍♂️',
    'COLLAPSE': '🧎‍♂️',
    'ENTROPY': '🤘',
    'THERMAL': '♨️',
    'DISSIPATION': '❤️‍🩹',
    'CHAOS_SPIKE': '💥',
    'NOISE_GRAIN': '🧂',
    'PHASE': '⭕',
    'OSCILLATION': '👋',
    'ROTATION': '🌪️',
    'PHASE_SHIFT': 'phase shift',
    'STANDING': '🌓',
    'OUT_PHASE': '🌑',
    'IN_PHASE': '🌕'
}

ORACLE = {
    'SELF': '🙋‍♂️',
    'RECURSIVE_SELF': '🧏‍♂️',
    'CLONE': '💇‍♂️',
    'COHERENT_SELF': '🙆‍♂️',
    'DECOHERING_SELF': '🙅‍♂️',
    'ENTROPIC_SELF': '🤦‍♂️',
    'LOOP': '🔄',
    'FREEZE': '☃️',
    'UNFREEZE': '⛄',
    'AUTO_REFINE': '🏁🙋‍♂️',
    'PHASE_SHIFT': '⚕️',
    'HALT': '⏹️',
    'FORCE_COLLAPSE': '⚡',
    'PROVEN': '💆‍♂️',
    'FALSE': '🙇‍♂️',
    'UNDECIDABLE': '🤷‍♂️',
    'AXIOM': '🪓',
    'PREDICT': '🔮',
    'HISTORY': '🔭',
    'HIDDEN_CONSTRAINT': '🧿',
    'CUT': '🔪',
    'REWRITE': '✍️',
    'MUTATE': '🧬',
    'FRACTAL_EVOLVE': '❄️🦍🚶‍♂️',
    'STOCHASTIC_MUTATE': '🧜‍♂️',
    'SELF_MUTATE': '🙋‍♂️🧞‍♂️',
    'STORE': '💾',
    'ERASE': '🗑️',
    'BLACK_HOLE': '🕳️',
    'BIND': '🪢',
    'LIFT': '⊶',
    'DESCEND': '⊷',
    'RECURSIVE_WRAP': '🔃⊶',
    'EMERGENT_LAW': '🌌',
    'NEW_PHASE_SEED': '🌱',
    'SELF_DESTRUCT': '🚬'
}

FOURIER = {
    'SINUSOID': '✒️🖋️',
    'COSINE': '🖋️🖊️',
    'CYCLE': '🚲',
    'COMPLEX_EXP': '🤑',
    'PHASOR': '🫆',
    'FREQ_X_N': '💢',
    'REAL': '🤖',
    'IMAG': '👽',
    'MAGNITUDE': '🧲',
    'PHASE': '🧬',
    'FORWARD_DFT': '↪️',
    'INVERSE_DFT': '⤵️',
    'CONV_MULT': '🛗',
    'WINDOW': '🪟',
    'SEGMENT': '🔛',
    'BIN': '🛄',
    'FFT_BUTTERFLY': '☸️',
    'SPECTRAL_EVOLUTION': '🕎',
    'AM': '🌝',
    'PM': '🌚',
    'SPECTROGRAM': '🌈'
}
